openapi: 3.0.3
info:
  title: AWS JS Practioner Course Backend
  contact:
    email: vadim_popov@epam.com
  version: 0.3.0
servers:
  - url: https://te38q1ychd.execute-api.eu-west-1.amazonaws.com/dev
    description: URL to Backend AWS API Gateway
paths:
  /products:
    get:
      summary: Returns list of all products
      description: Returns list of all products
      operationId: getProductsList
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: {
                type: "array",
                items: {
                  $ref: '#/components/schemas/Product'
                }
              } 

  /products/{productId}:
    get:
      summary: Get product by Id
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Nanty Narking
        year:
          type: number
          format: YYYY
          example: 2019
        author:
          type: string
          example: Martin Wallace
        description:
          type: string
          example: Immersed deeply in the world of Dickens’s and Doyle’s literature, Nanty Narking moves you into the realities of the myths and legends of the Victorian era. The events in the game are tied to real and fictional characters and places in Victorian London The same London which inspired so many stories…
        price:
          type: number
          example: 39
        img:
          type: string
          example: https://cf.geekdo-images.com/QVnxAPBc7rhzQ90WGH-G_Q__itemrep/img/5n2PUYy7ySY4R9QnIcm1yDdXY_s=/fit-in/246x300/filters:strip_icc()/pic6111342.png
        count:
          type: number
          example: 4